apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: forever
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: kiran22sktech/forever-admin
          imagePullPolicy: Always
          ports:
            - containerPort: 80