apiVersion: v1
kind: Namespace
metadata:
  name: forever
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: forever
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: forever
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: forever
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: forever-backend:local
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb:27017"
            - name: NODE_ENV
              value: "production"
          envFrom:
            - secretRef:
                name: forever-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: forever
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30400
